"""
setup.py — Interactive setup wizard
====================================
Guides the user through entering credentials and writes a .env file.

    python setup.py
"""

import os
import sys
from pathlib import Path


# ── ANSI colours ──────────────────────────────────────────────────────────────
CYAN = "\033[96m"
GREEN = "\033[92m"
YELLOW = "\033[93m"
BOLD = "\033[1m"
RESET = "\033[0m"


def header():
    print(f"""
{BOLD}╔══════════════════════════════════════════════════╗
║       Telegram News Bot — Setup Wizard           ║
╚══════════════════════════════════════════════════╝{RESET}

This wizard creates your {CYAN}.env{RESET} configuration file.
You can re-run it at any time to update credentials.
""")


def ask(prompt: str, default: str = "") -> str:
    """Prompt the user for input with an optional default value."""
    display_default = f"[{default}]" if default else ""
    full_prompt = f"  {CYAN}{prompt}{RESET} {display_default}: "

    while True:
        value = input(full_prompt).strip()

        if value:
            return value
        if default:
            return default
        print(f"  {YELLOW}This field is required.{RESET}")


def confirm(prompt: str) -> bool:
    resp = input(f"  {prompt} [y/N]: ").strip().lower()
    return resp in ("y", "yes")


def section(title: str):
    print(f"\n{BOLD}── {title} {'─' * (46 - len(title))}{RESET}")


def main():
    header()

    env_path = Path(".env")
    if env_path.exists():
        print(f"  An existing {CYAN}.env{RESET} file was found.")
        if not confirm("Overwrite it?"):
            print("  Setup cancelled. Your existing .env was not changed.")
            sys.exit(0)

    # ── Step 1: Telegram ──────────────────────────────────────────────────────
    section("Step 1 of 4 — Telegram Bot Token")
    print("""  How to get a bot token:
    1. Open Telegram and search for @BotFather
    2. Send /newbot and follow the prompts
    3. Copy the token that looks like: 1234567890:ABCdef...
""")
    bot_token = ask("Paste your Bot Token")

    # ── Step 2: Channel ───────────────────────────────────────────────────────
    section("Step 2 of 4 — Telegram Channel ID")
    print("""  How to get your channel ID:
    • Public channel:  use @your_channel_username
    • Private channel: forward a message to @userinfobot to get the numeric ID
      (format: -1001234567890)

  Make sure your bot is added as an Administrator of the channel.
""")
    channel_id = ask("Channel username or ID (e.g. @mychannel)")

    # ── Step 3: NewsAPI ───────────────────────────────────────────────────────
    section("Step 3 of 4 — NewsAPI Key")
    print("""  How to get a free NewsAPI key:
    1. Go to https://newsapi.org/register
    2. Sign up with your email
    3. Copy the API key from your account dashboard
""")
    newsapi_key = ask("Paste your NewsAPI key")

    # ── Step 4: Bot behaviour ─────────────────────────────────────────────────
    section("Step 4 of 4 — Bot Configuration")

    keywords_default = "Bitcoin,MSFT,Apple,Tesla,AI,OpenAI"
    print(f"\n  Keywords to track (comma-separated):")
    keywords = ask("Keywords", default=keywords_default)

    print(f"\n  How often to fetch and post news:")
    interval = ask("Interval in minutes", default="30")

    print(f"\n  Max articles to post per cycle:")
    max_articles = ask("Max articles per cycle", default="5")

    print(f"\n  Category-based headlines (optional — leave blank to skip):")
    print(f"  Options: business, entertainment, general, health, science, sports, technology")
    category = ask("Category (or press Enter to skip)", default="").strip()

    country = "us"
    if category:
        country = ask("Country code for headlines", default="us")

    # ── Write .env ────────────────────────────────────────────────────────────
    lines = [
        "# Generated by setup.py — edit manually or re-run setup.py",
        "",
        f"TELEGRAM_BOT_TOKEN={bot_token}",
        f"TELEGRAM_CHANNEL_ID={channel_id}",
        f"NEWSAPI_KEY={newsapi_key}",
        "",
        f"KEYWORDS={keywords}",
        f"INTERVAL_MINUTES={interval}",
        f"MAX_ARTICLES_PER_CYCLE={max_articles}",
    ]
    if category:
        lines += [
            "",
            f"NEWS_CATEGORY={category}",
            f"NEWS_COUNTRY={country}",
        ]

    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"""
{GREEN}✓ .env file written successfully!{RESET}

Next steps:
  1. Verify credentials:   {CYAN}python test_bot.py{RESET}
  2. Start the bot:        {CYAN}python telegram_news_bot.py{RESET}
""")


if __name__ == "__main__":
    main()
